#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}NixOS${bold}${normal}"
nix flake update --flake $(dirname $0)/nixos

echo ""

echo "${bold}Home Manager${bold}${normal}"
nix flake update --flake $(dirname $0)/home-manager