background #101010
foreground #a3a3a3
cursor #aaaaaa
selection_background #453a39
color0 #171a1a
color8 #3d3f40
color1 #f92672
color9 #ff669d
color2 #a2e222
color10 #beed5f
color3 #fd9419
color11 #e6db74
color4 #3cd2ef
color12 #8fe0ef
color5 #8f59fe
color13 #ba98fe
color6 #d915ba
color14 #d982cb
color7 #cfcfc9
color15 #f8f8f2
selection_foreground #101010
