# ░█░█░█░█░█▀█░█▀▄░█▀█░█▀█░█▀█░█▀▀░█▀▄
# ░█▀█░░█░░█▀▀░█▀▄░█▀▀░█▀█░█▀▀░█▀▀░█▀▄
# ░▀░▀░░▀░░▀░░░▀░▀░▀░░░▀░▀░▀░░░▀▀▀░▀░▀

preload = $HOME/Pictures/Wallpaper/wallpaper
wallpaper = ,$HOME/Pictures/Wallpaper/wallpaper
